apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: lobsters-script-post-to-twitter
  labels:
    app: lobsters
    component: script
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: lobsters
            component: rake
        spec:
          containers:
            - name: lobsters
              image: mstrzele/lobsters:latest
              env:
                - name: DATABASE_URL
                  valueFrom:
                    secretKeyRef:
                      name: lobsters-rails-server
                      key: DATABASE_URL
              command: ["bundle"]
              args: ["exec", "ruby", "script/post_to_twitter"]
          restartPolicy: OnFailure
  concurrencyPolicy: Forbid
