apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: lobsters
  labels:
    app: lobsters
spec:
  rules:
    - http:
        paths:
          - path: /*
            backend:
              serviceName: lobsters-rails-server
              servicePort: 3000
