apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      initContainers:
        - name: busybox
          image: busybox
          command: ["rm"]
          args: ["-fr", "/var/lib/mysql/lost+found"]
          volumeMounts:
            - name: mysql
              mountPath: /var/lib/mysql
      containers:
        - name: mysql
          image: mysql/mysql-server:5.7.21
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: mysql
              mountPath: /var/lib/mysql
          envFrom:
            - secretRef:
                name: mysql
      volumes:
        - name: mysql
          gcePersistentDisk:
            pdName: disk-1
  strategy:
    type: Recreate
    rollingUpdate:
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  selector:
    app: mysql
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
