apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: php-app
  namespace: default
spec:
  maxReplicas: 10
  minReplicas: 1
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: php-app
  targetCPUUtilizationPercentage: 30
