apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-app
  labels:
    app: php-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: php-app
  template:
    metadata:
      labels:
        app: php-app
    spec:
      containers:
        - name: php-app
          image: lukaszbielinski/php-app:latest
          ports:
            - containerPort: 80
          resources:
            limits:
              memory: "100Mi"
              cpu: "50m"
            requests:
              memory: "100Mi"
              cpu: "50m"
---
apiVersion: v1
kind: Service
metadata:
  name: php-app
  labels:
    app: php-app
spec:
  selector:
    app: php-app
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
