apiVersion: apps/v1
kind: Deployment
metadata:
  name: lobsters-rails-server
  labels:
    app: lobsters
    component: rails
spec:
  selector:
    matchLabels:
      app: lobsters
      component: rails
  template:
    metadata:
      labels:
        app: lobsters
        component: rails
    spec:
      containers:
        - name: lobsters
          image: mstrzele/lobsters:latest
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: lobsters-rails-server
                  key: DATABASE_URL
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: lobsters-rails-server
  labels:
    app: lobsters
    component: rails
spec:
  selector:
    app: lobsters
    component: rails
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: LoadBalancer
